### ISSUE TITLE
I am using multimc and i think there is a mapping issue

### ISSUE THREAD

**Issue by lolzake** [fr1kin/ForgeHax#104]
[01:30:33] [main/INFO] [ForgeHaxASM]: Using build mapping "1.12_snapshot_20171003"
[01:30:33] [main/ERROR] [ForgeHaxASM]: Application data folder does not exist and cannot be created.
[01:30:33] [main/ERROR] [ForgeHaxAsmStackTrace]: com.matt.forgehax.asm.utils.remapping.MCPMappingLoader$CantLoadMCPMappingException: Application data folder does not exist and cannot be created.

And then theres a bunch of errors because of this

[01:30:33] [main/ERROR] [ForgeHaxAsmStackTrace]: com.matt.forgehax.asm.utils.remapping.MCPMappingLoader$CantLoadMCPMappingException: Application data folder does not exist and cannot be created.
	at com.matt.forgehax.asm.utils.remapping.MCPMappingLoader.getSubDirForZip(MCPMappingLoader.java:82)
	at com.matt.forgehax.asm.utils.remapping.MCPMappingLoader.<init>(MCPMappingLoader.java:39)
	at com.matt.forgehax.asm.utils.remapping.ObfuscatedStateMapper.<init>(ObfuscatedStateMapper.java:42)
	at com.matt.forgehax.asm.utils.remapping.ObfuscatedStateMapper.getInstance(ObfuscatedStateMapper.java:29)
	at com.matt.forgehax.asm.utils.environment.RuntimeState.getMapper(RuntimeState.java:65)
	at com.matt.forgehax.asm.ASMCommon.<clinit>(ASMCommon.java:11)
	at com.matt.forgehax.asm.utils.asmtype.builders.ASMClassBuilder.attemptAutoAssign(ASMClassBuilder.java:55)
	at com.matt.forgehax.asm.utils.asmtype.builders.ASMClassBuilder.build(ASMClassBuilder.java:60)
	at com.matt.forgehax.asm.TypesMc$Classes.<clinit>(TypesMc.java:19)
	at com.matt.forgehax.asm.patches.BlockPatch.<init>(BlockPatch.java:14)
	at com.matt.forgehax.asm.ForgeHaxTransformer.<init>(ForgeHaxTransformer.java:27)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)
	at java.lang.reflect.Constructor.newInstance(Unknown Source)
	at java.lang.Class.newInstance(Unknown Source)
	at net.minecraftforge.fml.common.asm.ASMTransformerWrapper$TransformerWrapper.<init>(ASMTransformerWrapper.java:243)
	at $wrapper.com.matt.forgehax.asm.ForgeHaxTransformer.<init>(Unknown Source)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)
	at java.lang.reflect.Constructor.newInstance(Unknown Source)
	at java.lang.Class.newInstance(Unknown Source)
	at net.minecraft.launchwrapper.LaunchClassLoader.registerTransformer(LaunchClassLoader.java:88)
	at net.minecraftforge.fml.relauncher.CoreModManager$FMLPluginWrapper.injectIntoClassLoader(CoreModManager.java:132)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:115)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:196)
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:231)
	at org.multimc.EntryPoint.listen(EntryPoint.java:143)
	at org.multimc.EntryPoint.main(EntryPoint.java:34)

[01:30:33] [main/INFO] [ForgeHaxASM]: Mapping data successfully initialize
[01:30:33] [main/INFO] [STDERR]: [org.multimc.onesix.OneSixLauncher:launchWithMainClass:199]: Failed to start Minecraft:
[01:30:33] [main/INFO] [STDERR]: [org.multimc.onesix.OneSixLauncher:launch:231]: java.lang.reflect.InvocationTargetException

There is more if you need

**Comment by lolzake** [comment]
Can you help me fix this , i use multimc because if u try normal minecraft , it doesnt make the mod folder , nor the forgehax folder

**Comment by lolzake** [comment]
I also saw this that u wrote : Sometimes when building, the config.properties resource will not be tokenized. This will break the tweaker because it wont know what mapping version to use. This can be fixed by cleaning your gradle and IDE build output and running setupDecompWorkspace again.


but idk how to do it

**Comment by lolzake** [comment]
I am sorry for not linking the full crash report before , but here it is 

https://textbin.host/p/?paste=tplnfLfMKb

**Comment by fr1kin** [comment]
The issue here is that the folder where mappings are stored cannot be created. If you run the multimc program under any Program Files folder windows 10 will limit its read/write capabilities. One solution is to run multimc.exe as administrator, this should temporarily fix the issue.

In the future I may decide to move the location the mappings are stored in.

**Comment by lolzake** [comment]
Thank you , this works
