### ISSUE TITLE
Crashes when using Impact with ForgeHax

### ISSUE THREAD

**Issue by devomaa** [fr1kin/ForgeHax#161]
ForgeHax looks like not liking Impact, can you guys fix it?
I would appreciate you guys fix it?

**Comment by babbaj** [comment]
i think you mean impact doesnt like forgehax

**Comment by devomaa** [comment]
(well whatever...)

**Comment by 0-x-2-2** [comment]
no crash report, no logs

**Comment by devomaa** [comment]
Here is the crash log:
---- Minecraft Crash Report ----

WARNING: coremods are present:
  CubicGenCoreMod (CubicWorldGen-1.12.2-0.0.39.1-SNAPSHOT-all.jar)
  ForgelinPlugin (Forgelin-1.8.4.jar)
  MalisisCorePlugin (malisiscore-1.12.2-6.5.1.jar)
  CubicChunksCoreMod (CubicChunks-1.12.2-0.0.970.0-SNAPSHOT-all.jar)
Contact their authors BEFORE contacting forge

// Shall we play a game?

Time: 1/5/20 8:51 PM
Description: Updating screen events

java.lang.NoSuchMethodError: net.malisis.core.client.gui.component.interaction.UITextField.setValidator(Lcom/google/common/base/Predicate;)Lnet/malisis/core/client/gui/component/interaction/UITextField;
	at io.github.opencubicchunks.cubicchunks.cubicgen.common.gui.MalisisGuiUtils.floatInput(MalisisGuiUtils.java:243)
	at io.github.opencubicchunks.cubicchunks.cubicgen.customcubic.gui.AdvancedTerrainShapeTab.<init>(AdvancedTerrainShapeTab.java:125)
	at io.github.opencubicchunks.cubicchunks.cubicgen.customcubic.gui.CustomCubicGui.reinit(CustomCubicGui.java:100)
	at io.github.opencubicchunks.cubicchunks.cubicgen.customcubic.gui.CustomCubicGui.construct(CustomCubicGui.java:92)
	at net.malisis.core.client.gui.MalisisGui.doConstruct(MalisisGui.java:150)
	at net.malisis.core.client.gui.MalisisGui.display(MalisisGui.java:705)
	at net.malisis.core.client.gui.MalisisGui.display(MalisisGui.java:694)
	at io.github.opencubicchunks.cubicchunks.cubicgen.customcubic.CustomCubicWorldType.onCustomizeButton(CustomCubicWorldType.java:104)
	at net.minecraft.client.gui.GuiCreateWorld.func_146284_a(GuiCreateWorld.java:317)
	at net.minecraft.client.gui.GuiScreen.redirect$actionPerformed$zlk000(GuiScreen.java:740)
	at net.minecraft.client.gui.GuiScreen.func_73864_a(GuiScreen.java:443)
	at net.minecraft.client.gui.GuiCreateWorld.func_73864_a(GuiCreateWorld.java:416)
	at net.minecraft.client.gui.GuiScreen.func_146274_d(GuiScreen.java:533)
	at net.minecraft.client.gui.GuiScreen.func_146269_k(GuiScreen.java:501)
	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1759)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1098)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:398)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:196)
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:231)
	at org.multimc.EntryPoint.listen(EntryPoint.java:143)
	at org.multimc.EntryPoint.main(EntryPoint.java:34)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
	at io.github.opencubicchunks.cubicchunks.cubicgen.common.gui.MalisisGuiUtils.floatInput(MalisisGuiUtils.java:243)
	at io.github.opencubicchunks.cubicchunks.cubicgen.customcubic.gui.AdvancedTerrainShapeTab.<init>(AdvancedTerrainShapeTab.java:125)
	at io.github.opencubicchunks.cubicchunks.cubicgen.customcubic.gui.CustomCubicGui.reinit(CustomCubicGui.java:100)
	at io.github.opencubicchunks.cubicchunks.cubicgen.customcubic.gui.CustomCubicGui.construct(CustomCubicGui.java:92)
	at net.malisis.core.client.gui.MalisisGui.doConstruct(MalisisGui.java:150)
	at net.malisis.core.client.gui.MalisisGui.display(MalisisGui.java:705)
	at net.malisis.core.client.gui.MalisisGui.display(MalisisGui.java:694)
	at io.github.opencubicchunks.cubicchunks.cubicgen.customcubic.CustomCubicWorldType.onCustomizeButton(CustomCubicWorldType.java:104)
	at net.minecraft.client.gui.GuiCreateWorld.func_146284_a(GuiCreateWorld.java:317)
	at net.minecraft.client.gui.GuiScreen.redirect$actionPerformed$zlk000(GuiScreen.java:740)
	at net.minecraft.client.gui.GuiScreen.func_73864_a(GuiScreen.java:443)
	at net.minecraft.client.gui.GuiCreateWorld.func_73864_a(GuiCreateWorld.java:416)
	at net.minecraft.client.gui.GuiScreen.func_146274_d(GuiScreen.java:533)
	at net.minecraft.client.gui.GuiScreen.func_146269_k(GuiScreen.java:501)

-- Affected screen --
Details:
	Screen name: net.minecraft.client.gui.GuiCreateWorld
Stacktrace:
	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1759)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1098)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:398)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:196)
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:231)
	at org.multimc.EntryPoint.listen(EntryPoint.java:143)
	at org.multimc.EntryPoint.main(EntryPoint.java:34)

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_231, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 1272599288 bytes (1213 MB) / 2399141888 bytes (2288 MB) up to 3817865216 bytes (3641 MB)
	JVM Flags: 3 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xms409m -Xmx4096m
	IntCache: cache: 0, tcache: 0, allocated: 13, tallocated: 95
	FML: MCP 9.42 Powered by Forge 14.23.5.2847 18 mods loaded, 17 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State  | ID              | Version                   | Source                                         | Signature                                |
	|:------ |:--------------- |:------------------------- |:---------------------------------------------- |:---------------------------------------- |
	| LCHIJA | minecraft       | 1.12.2                    | minecraft.jar                                  | None                                     |
	| LCHIJA | mcp             | 9.42                      | minecraft.jar                                  | None                                     |
	| LCHIJA | FML             | 8.0.99.99                 | forge-1.12.2-14.23.5.2847-universal.jar        | None                                     |
	| LCHIJA | forge           | 14.23.5.2847              | forge-1.12.2-14.23.5.2847-universal.jar        | None                                     |
	| LCHIJA | forgelin        | 1.8.4                     | Forgelin-1.8.4.jar                             | None                                     |
	| LCHIJA | betterportals   | 0.3.7.4                   | betterportals-0.3.7.4.jar                      | None                                     |
	| LCHIJA | cctweaked       | 1.86.0                    | cc-tweaked-1.12.2-1.86.0.jar                   | None                                     |
	| LCHIJA | computercraft   | 1.86.0                    | cc-tweaked-1.12.2-1.86.0.jar                   | None                                     |
	| LCHIJA | cubicchunks     | 1.12.2-0.0.970.0-SNAPSHOT | CubicChunks-1.12.2-0.0.970.0-SNAPSHOT-all.jar  | None                                     |
	| LCHIJA | cubicgen        | 1.12.2-0.0.39.1-SNAPSHOT  | CubicWorldGen-1.12.2-0.0.39.1-SNAPSHOT-all.jar | None                                     |
	| LCHIJA | lunatriuscore   | 1.2.0.42                  | LunatriusCore-1.12.2-1.2.0.42-universal.jar    | None                                     |
	| LCHIJA | malisiscore     | 1.12.2-6.5.1-SNAPSHOT     | malisiscore-1.12.2-6.5.1.jar                   | None                                     |
	| LCHIJA | plethora-core   | 1.2.2                     | plethora-1.12.2-1.2.2(1).jar                   | None                                     |
	| LCHIJA | plethora        | 1.2.2                     | plethora-1.12.2-1.2.2(1).jar                   | None                                     |
	| LCHIJA | redstoneflux    | 2.1.0                     | RedstoneFlux-1.12-2.1.0.6-universal.jar        | 8a6abf2cb9e141b866580d369ba6548732eff25f |
	| LCHIJA | schematica      | 1.8.0.169                 | Schematica-1.12.2-1.8.0.169-universal.jar      | None                                     |
	| LCHIJA | sgcraft         | 1.13.2                    | SGCraft-2.0.2.jar                              | None                                     |
	| UD     | cubicchunkscore | @@VERSION@@               | minecraft.jar                                  | None                                     |

	Loaded coremods (and transformers): 
CubicGenCoreMod (CubicWorldGen-1.12.2-0.0.39.1-SNAPSHOT-all.jar)
  
ForgelinPlugin (Forgelin-1.8.4.jar)
  
MalisisCorePlugin (malisiscore-1.12.2-6.5.1.jar)
  
CubicChunksCoreMod (CubicChunks-1.12.2-0.0.970.0-SNAPSHOT-all.jar)
  
	GL info: ' Vendor: 'NVIDIA Corporation' Version: '4.6.0 NVIDIA 431.87' Renderer: 'GeForce RTX 2060/PCIe/SSE2'
	Launched Version: MultiMC5
	LWJGL: 2.9.4
	OpenGL: GeForce RTX 2060/PCIe/SSE2 GL version 4.6.0 NVIDIA 431.87, NVIDIA Corporation
	GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Packs: 
	Current Language: English (US)
	Profiler Position: N/A (disabled)
	CPU: 8x AMD Ryzen 7 3750H with Radeon Vega Mobile Gfx

**Comment by 0-x-2-2** [comment]
confirmed. user error

**Comment by 0-x-2-2** [comment]
this is unrelated to forgehax or impact

**Comment by JamTheAdventurer** [comment]
bruh

**Comment by pjalsGit** [comment]
god i was such a clown back then
