### ISSUE TITLE
ForgeHax crash

### ISSUE THREAD

**Issue by Rithmatist** [fr1kin/ForgeHax#266]
I get this when i try to run the modpack "Valhelsia 2" (1.15.2)

```
[15:33:06] [main/INFO]: ModLauncher running: args [--username, GuardDaos, --version, forge-31.2.46, --gameDir, C:\Users\Shadow\Twitch\Minecraft\Instances\Valhelsia 2, --assetsDir, C:\Users\Shadow\Twitch\Minecraft\Install\assets, --assetIndex, 1.15, --uuid, 893d6324fa9b488dad8408138ea8e0da, --accessToken, ????????, --userType, mojang, --versionType, release, --width, 1024, --height, 768, --launchTarget, fmlclient, --fml.forgeVersion, 31.2.46, --fml.mcVersion, 1.15.2, --fml.forgeGroup, net.minecraftforge, --fml.mcpVersion, 20200515.085601]
[15:33:06] [main/INFO]: ModLauncher 5.1.2+70+master.2845bb9 starting: java version 1.8.0_51 by Oracle Corporation
[15:33:07] [main/INFO]: ForgeHaxCore initializing
[15:33:07] [main/INFO]: Added Lets Encrypt root certificates as additional trust
[15:33:07] [main/WARN]: ForgeHaxCore found Mixin. Some patches may not apply.
[15:33:07] [main/INFO]: SpongePowered MIXIN Subsystem Version=0.8.2 Source=file:/C:/Users/Shadow/Twitch/Minecraft/Install/libraries/org/spongepowered/mixin/0.8.2/mixin-0.8.2.jar Service=ModLauncher Env=CLIENT
[15:33:08] [main/INFO]: [dev.fiki.forgehax.asm.utils.ForgehaxModLocator:<init>:14]: Created ForgehaxModLocator
[15:33:09] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:1052]: java.lang.NoSuchMethodError: net.minecraftforge.fml.loading.moddiscovery.ModFile.<init>(Ljava/nio/file/Path;Lnet/minecraftforge/forgespi/locating/IModLocator;)V
[15:33:09] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at dev.fiki.forgehax.asm.utils.ForgehaxModLocator.lambda$scanMods$1(ForgehaxModLocator.java:21)
[15:33:09] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at dev.fiki.forgehax.asm.utils.ForgehaxModLocator$$Lambda$251/1899141525.apply(Unknown Source)
[15:33:09] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at java.util.Optional.map(Optional.java:215)
[15:33:09] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at dev.fiki.forgehax.asm.utils.ForgehaxModLocator.scanMods(ForgehaxModLocator.java:20)
[15:33:09] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at net.minecraftforge.fml.loading.moddiscovery.ModDiscoverer$$Lambda$219/1351478315.apply(Unknown Source)
[15:33:09] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
[15:33:09] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at java.util.stream.ReferencePipeline$11$1.accept(ReferencePipeline.java:373)
[15:33:09] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1374)
[15:33:09] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:512)
[15:33:09] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:502)
[15:33:09] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708)
[15:33:09] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
[15:33:09] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:499)
[15:33:09] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at net.minecraftforge.fml.loading.moddiscovery.ModDiscoverer.discoverMods(ModDiscoverer.java:107)
[15:33:09] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at net.minecraftforge.fml.loading.FMLLoader.beginModScan(FMLLoader.java:213)
[15:33:09] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at net.minecraftforge.fml.loading.FMLServiceProvider.runScan(FMLServiceProvider.java:107)
[15:33:09] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at cpw.mods.modlauncher.TransformationServiceDecorator.runScan(TransformationServiceDecorator.java:111)
[15:33:09] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at cpw.mods.modlauncher.TransformationServicesHandler.lambda$runScanningTransformationServices$8(TransformationServicesHandler.java:115)
[15:33:09] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at cpw.mods.modlauncher.TransformationServicesHandler$$Lambda$189/837457281.apply(Unknown Source)
[15:33:09] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at java.util.stream.ReferencePipeline$7$1.accept(ReferencePipeline.java:267)
[15:33:09] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at java.util.HashMap$ValueSpliterator.forEachRemaining(HashMap.java:1612)
[15:33:09] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:512)
[15:33:09] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:502)
[15:33:09] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708)
[15:33:09] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
[15:33:09] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:499)
[15:33:09] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at cpw.mods.modlauncher.TransformationServicesHandler.runScanningTransformationServices(TransformationServicesHandler.java:116)
[15:33:09] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at cpw.mods.modlauncher.TransformationServicesHandler.initializeTransformationServices(TransformationServicesHandler.java:63)
[15:33:09] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at cpw.mods.modlauncher.Launcher.run(Launcher.java:75)
[15:33:09] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at cpw.mods.modlauncher.Launcher.main(Launcher.java:65)

```

**Comment by fr1kin** [comment]
Probably #235
