### ISSUE TITLE
[1.15.2] Crash on newer forge

### ISSUE THREAD

**Issue by mahoshojoHCG** [fr1kin/ForgeHax#272]
On forge 31.1.30，everything works fine, but on forge newer than 31.2, I got
```
[09十二月2020 15:17:23.129] [main/INFO] [STDOUT/]: [dev.fiki.forgehax.asm.utils.ForgehaxModLocator:<init>:14]: Created ForgehaxModLocator
[09十二月2020 15:17:23.689] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1052]: java.lang.NoSuchMethodError: net.minecraftforge.fml.loading.moddiscovery.ModFile.<init>(Ljava/nio/file/Path;Lnet/minecraftforge/forgespi/locating/IModLocator;)V
[09十二月2020 15:17:23.689] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at dev.fiki.forgehax.asm.utils.ForgehaxModLocator.lambda$scanMods$1(ForgehaxModLocator.java:21)
[09十二月2020 15:17:23.690] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at java.util.Optional.map(Optional.java:215)
[09十二月2020 15:17:23.690] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at dev.fiki.forgehax.asm.utils.ForgehaxModLocator.scanMods(ForgehaxModLocator.java:20)
[09十二月2020 15:17:23.690] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
[09十二月2020 15:17:23.691] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at java.util.stream.ReferencePipeline$11$1.accept(ReferencePipeline.java:440)
[09十二月2020 15:17:23.691] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1384)
[09十二月2020 15:17:23.691] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:482)
[09十二月2020 15:17:23.692] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:472)
[09十二月2020 15:17:23.692] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708)
[09十二月2020 15:17:23.692] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
[09十二月2020 15:17:23.692] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:566)
[09十二月2020 15:17:23.693] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at net.minecraftforge.fml.loading.moddiscovery.ModDiscoverer.discoverMods(ModDiscoverer.java:107)
[09十二月2020 15:17:23.693] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at net.minecraftforge.fml.loading.FMLLoader.beginModScan(FMLLoader.java:213)
[09十二月2020 15:17:23.694] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at net.minecraftforge.fml.loading.FMLServiceProvider.runScan(FMLServiceProvider.java:107)
[09十二月2020 15:17:23.694] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at cpw.mods.modlauncher.TransformationServiceDecorator.runScan(TransformationServiceDecorator.java:111)
[09十二月2020 15:17:23.694] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at cpw.mods.modlauncher.TransformationServicesHandler.lambda$runScanningTransformationServices$8(TransformationServicesHandler.java:115)
[09十二月2020 15:17:23.695] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at java.util.stream.ReferencePipeline$7$1.accept(ReferencePipeline.java:269)
[09十二月2020 15:17:23.695] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at java.util.HashMap$ValueSpliterator.forEachRemaining(HashMap.java:1628)
[09十二月2020 15:17:23.695] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:482)
[09十二月2020 15:17:23.695] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:472)
[09十二月2020 15:17:23.695] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708)
[09十二月2020 15:17:23.696] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
[09十二月2020 15:17:23.696] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:566)
[09十二月2020 15:17:23.696] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at cpw.mods.modlauncher.TransformationServicesHandler.runScanningTransformationServices(TransformationServicesHandler.java:116)
[09十二月2020 15:17:23.696] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at cpw.mods.modlauncher.TransformationServicesHandler.initializeTransformationServices(TransformationServicesHandler.java:63)
[09十二月2020 15:17:23.696] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at cpw.mods.modlauncher.Launcher.run(Launcher.java:75)
[09十二月2020 15:17:23.697] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at cpw.mods.modlauncher.Launcher.main(Launcher.java:65)

```

**Comment by fr1kin** [comment]
#235
