### ISSUE TITLE
Forge says ForgeHax failed to initialize 

### ISSUE THREAD

**Issue by SomeDude1233** [fr1kin/ForgeHax#275]
I'm using 1.16.4, works ok without ForgeHax. Here's the crash report:

---- Minecraft Crash Report ----
// Daisy, daisy...

Time: 12/12/20 11:11 AM
Description: Mod loading error has occurred

java.lang.Exception: Mod Loading has failed
	at net.minecraftforge.fml.CrashReportExtender.dumpModLoadingCrashReport(CrashReportExtender.java:85) [?:?] {re:classloading}
	at net.minecraftforge.fml.client.ClientModLoader.completeModLoading(ClientModLoader.java:188) [?:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.lambda$null$1(Minecraft.java:508) [?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft$$Lambda$4030/1152308900.run(Unknown Source) [?:?] {}
	at net.minecraft.util.Util.func_215077_a(Util.java:418) [?:?] {re:classloading,xf:OptiFine:default}
	at net.minecraft.client.Minecraft.lambda$new$2(Minecraft.java:504) [?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft$$Lambda$3594/1171097095.accept(Unknown Source) [?:?] {}
	at net.minecraft.client.gui.ResourceLoadProgressGui.func_230430_a_(ResourceLoadProgressGui.java:172) [?:?] {re:classloading,xf:OptiFine:default}
	at net.minecraft.client.renderer.GameRenderer.func_195458_a(GameRenderer.java:802) [?:?] {re:classloading,pl:accesstransformer:B,xf:OptiFine:default}
	at net.minecraft.client.Minecraft.func_195542_b(Minecraft.java:976) [?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:607) [?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.main.Main.main(Main.java:184) [?:?] {re:classloading,pl:runtimedistcleaner:A}
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_51] {}
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_51] {}
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_51] {}
	at java.lang.reflect.Method.invoke(Method.java:497) ~[?:1.8.0_51] {}
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider.lambda$launchService$0(FMLClientLaunchProvider.java:51) [forge-1.16.4-35.1.0.jar:35.1] {}
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider$$Lambda$452/465233746.call(Unknown Source) [forge-1.16.4-35.1.0.jar:35.1] {}
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-8.0.6.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54) [modlauncher-8.0.6.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72) [modlauncher-8.0.6.jar:?] {}
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:82) [modlauncher-8.0.6.jar:?] {}
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:66) [modlauncher-8.0.6.jar:?] {}

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at dev.fiki.forgehax.api.modloader.di.providers.ReflectionProviders$FieldProvider.lambda$getInstance$1(ReflectionProviders.java:62) ~[?:3.2.0-e742d4aa] {re:classloading}
-- MOD forgehax --
Details:
	Caused by 0: java.lang.Error: ForgeHax failed to initialize
		at dev.fiki.forgehax.main.ForgeHax.setup(ForgeHax.java:127) ~[?:3.2.0-e742d4aa] {re:classloading}
		at dev.fiki.forgehax.main.ForgeHax$$Lambda$3112/792725227.accept(Unknown Source) ~[?:?] {}
		at net.minecraftforge.eventbus.EventBus.doCastFilter(EventBus.java:247) ~[eventbus-3.0.5-service.jar:?] {}
		at net.minecraftforge.eventbus.EventBus.lambda$addListener$11(EventBus.java:239) ~[eventbus-3.0.5-service.jar:?] {}
		at net.minecraftforge.eventbus.EventBus$$Lambda$2935/1994984869.invoke(Unknown Source) ~[?:?] {}
		at net.minecraftforge.eventbus.EventBus.post(EventBus.java:297) ~[eventbus-3.0.5-service.jar:?] {}
		at net.minecraftforge.fml.javafmlmod.FMLModContainer.acceptEvent(FMLModContainer.java:120) ~[?:35.1] {re:classloading}
		at net.minecraftforge.fml.ModContainer.lambda$buildTransitionHandler$4(ModContainer.java:121) ~[?:?] {re:classloading}
		at net.minecraftforge.fml.ModContainer$$Lambda$3106/2040008077.run(Unknown Source) ~[?:?] {}
		at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1618) ~[?:1.8.0_51] {}
		at java.util.concurrent.CompletableFuture$AsyncRun.exec(CompletableFuture.java:1610) ~[?:1.8.0_51] {}
		at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289) ~[?:1.8.0_51] {}
		at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056) ~[?:1.8.0_51] {}
		at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1689) ~[?:1.8.0_51] {re:computing_frames}
		at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157) ~[?:1.8.0_51] {}

	Caused by 1: dev.fiki.forgehax.api.modloader.di.providers.DependencyProvider$FailedToInitializeException: Failed to get instance of class: dev.fiki.forgehax.api.reflection.ReflectionTools
		at dev.fiki.forgehax.api.modloader.di.providers.DependencyProvider$LoadChain.getOrCreate(DependencyProvider.java:86) ~[?:3.2.0-e742d4aa] {re:classloading}
		at dev.fiki.forgehax.api.modloader.di.providers.SingletonDependency.getInstance(SingletonDependency.java:69) ~[?:3.2.0-e742d4aa] {re:classloading}
		at dev.fiki.forgehax.api.modloader.di.providers.DependencyProvider.getInstance(DependencyProvider.java:30) ~[?:3.2.0-e742d4aa] {re:classloading}
		at dev.fiki.forgehax.api.modloader.di.DependencyInjector.getSingletonInstance(DependencyInjector.java:138) ~[?:3.2.0-e742d4aa] {re:classloading}
		at dev.fiki.forgehax.api.modloader.di.DependencyInjector$$Lambda$3896/455646417.apply(Unknown Source) ~[?:?] {}
		at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193) ~[?:1.8.0_51] {}
		at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:175) ~[?:1.8.0_51] {}
		at java.util.TreeMap$KeySpliterator.forEachRemaining(TreeMap.java:2742) ~[?:1.8.0_51] {}
		at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:512) ~[?:1.8.0_51] {}
		at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:502) ~[?:1.8.0_51] {}
		at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:151) ~[?:1.8.0_51] {}
		at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:174) ~[?:1.8.0_51] {}
		at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:1.8.0_51] {}
		at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:418) ~[?:1.8.0_51] {}
		at dev.fiki.forgehax.api.modloader.ModManager.startupMods(ModManager.java:114) ~[?:3.2.0-e742d4aa] {re:classloading}
		at dev.fiki.forgehax.main.ForgeHax.setup(ForgeHax.java:118) ~[?:3.2.0-e742d4aa] {re:classloading}
		at dev.fiki.forgehax.main.ForgeHax$$Lambda$3112/792725227.accept(Unknown Source) ~[?:?] {}
		at net.minecraftforge.eventbus.EventBus.doCastFilter(EventBus.java:247) ~[eventbus-3.0.5-service.jar:?] {}
		at net.minecraftforge.eventbus.EventBus.lambda$addListener$11(EventBus.java:239) ~[eventbus-3.0.5-service.jar:?] {}
		at net.minecraftforge.eventbus.EventBus$$Lambda$2935/1994984869.invoke(Unknown Source) ~[?:?] {}
		at net.minecraftforge.eventbus.EventBus.post(EventBus.java:297) ~[eventbus-3.0.5-service.jar:?] {}
		at net.minecraftforge.fml.javafmlmod.FMLModContainer.acceptEvent(FMLModContainer.java:120) ~[?:35.1] {re:classloading}
		at net.minecraftforge.fml.ModContainer.lambda$buildTransitionHandler$4(ModContainer.java:121) ~[?:?] {re:classloading}
		at net.minecraftforge.fml.ModContainer$$Lambda$3106/2040008077.run(Unknown Source) ~[?:?] {}
		at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1618) ~[?:1.8.0_51] {}
		at java.util.concurrent.CompletableFuture$AsyncRun.exec(CompletableFuture.java:1610) ~[?:1.8.0_51] {}
		at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289) ~[?:1.8.0_51] {}
		at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056) ~[?:1.8.0_51] {}
		at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1689) ~[?:1.8.0_51] {re:computing_frames}
		at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157) ~[?:1.8.0_51] {}

	Caused by 2: dev.fiki.forgehax.api.modloader.di.providers.DependencyProvider$FailedToInitializeException: Failed to get instance of class: dev.fiki.forgehax.api.reflection.types.ReflectionField
		at dev.fiki.forgehax.api.modloader.di.providers.DependencyProvider$LoadChain.getOrCreate(DependencyProvider.java:86) ~[?:3.2.0-e742d4aa] {re:classloading}
		at dev.fiki.forgehax.api.modloader.di.providers.SingletonDependency.getInstance(SingletonDependency.java:69) ~[?:3.2.0-e742d4aa] {re:classloading}
		at dev.fiki.forgehax.api.modloader.di.providers.DependencyProvider$LoadChain.getOrCreate(DependencyProvider.java:84) ~[?:3.2.0-e742d4aa] {re:classloading}
		at dev.fiki.forgehax.api.modloader.di.providers.SingletonDependency.getInstance(SingletonDependency.java:69) ~[?:3.2.0-e742d4aa] {re:classloading}
		at dev.fiki.forgehax.api.modloader.di.providers.DependencyProvider.getInstance(DependencyProvider.java:30) ~[?:3.2.0-e742d4aa] {re:classloading}
		at dev.fiki.forgehax.api.modloader.di.DependencyInjector.getSingletonInstance(DependencyInjector.java:138) ~[?:3.2.0-e742d4aa] {re:classloading}
		at dev.fiki.forgehax.api.modloader.di.DependencyInjector$$Lambda$3896/455646417.apply(Unknown Source) ~[?:?] {}
		at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193) ~[?:1.8.0_51] {}
		at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:175) ~[?:1.8.0_51] {}
		at java.util.TreeMap$KeySpliterator.forEachRemaining(TreeMap.java:2742) ~[?:1.8.0_51] {}
		at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:512) ~[?:1.8.0_51] {}
		at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:502) ~[?:1.8.0_51] {}
		at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:151) ~[?:1.8.0_51] {}
		at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:174) ~[?:1.8.0_51] {}
		at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:1.8.0_51] {}
		at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:418) ~[?:1.8.0_51] {}
		at dev.fiki.forgehax.api.modloader.ModManager.startupMods(ModManager.java:114) ~[?:3.2.0-e742d4aa] {re:classloading}
		at dev.fiki.forgehax.main.ForgeHax.setup(ForgeHax.java:118) ~[?:3.2.0-e742d4aa] {re:classloading}
		at dev.fiki.forgehax.main.ForgeHax$$Lambda$3112/792725227.accept(Unknown Source) ~[?:?] {}
		at net.minecraftforge.eventbus.EventBus.doCastFilter(EventBus.java:247) ~[eventbus-3.0.5-service.jar:?] {}
		at net.minecraftforge.eventbus.EventBus.lambda$addListener$11(EventBus.java:239) ~[eventbus-3.0.5-service.jar:?] {}
		at net.minecraftforge.eventbus.EventBus$$Lambda$2935/1994984869.invoke(Unknown Source) ~[?:?] {}
		at net.minecraftforge.eventbus.EventBus.post(EventBus.java:297) ~[eventbus-3.0.5-service.jar:?] {}
		at net.minecraftforge.fml.javafmlmod.FMLModContainer.acceptEvent(FMLModContainer.java:120) ~[?:35.1] {re:classloading}
		at net.minecraftforge.fml.ModContainer.lambda$buildTransitionHandler$4(ModContainer.java:121) ~[?:?] {re:classloading}
		at net.minecraftforge.fml.ModContainer$$Lambda$3106/2040008077.run(Unknown Source) ~[?:?] {}
		at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1618) ~[?:1.8.0_51] {}
		at java.util.concurrent.CompletableFuture$AsyncRun.exec(CompletableFuture.java:1610) ~[?:1.8.0_51] {}
		at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289) ~[?:1.8.0_51] {}
		at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056) ~[?:1.8.0_51] {}
		at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1689) ~[?:1.8.0_51] {re:computing_frames}
		at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157) ~[?:1.8.0_51] {}

	Mod File: ForgeHax-1.16.4-3.2.0-e742d4aa.jar
	Failure message: ForgeHax (forgehax) encountered an error during the sided_setup event phase
		java.lang.Error: ForgeHax failed to initialize
	Mod Version: 3.2.0-e742d4aa
	Mod Issue URL: https://github.com/fr1kin/ForgeHax/issues
	Exception message: dev.fiki.forgehax.api.modloader.di.providers.DependencyProvider$FailedToInitializeException: Could not find any FieldMapping annotation: DependencyProvider.BuildContext(qualifier=null, contextClass=null, contextParameter=final dev.fiki.forgehax.api.reflection.types.ReflectionField<java.lang.Double> CPacketPlayer_y, contextField=public final dev.fiki.forgehax.api.reflection.types.ReflectionField dev.fiki.forgehax.api.reflection.ReflectionTools.CPacketPlayer_y)
Stacktrace:
	at dev.fiki.forgehax.api.modloader.di.providers.ReflectionProviders$FieldProvider.lambda$getInstance$1(ReflectionProviders.java:62) ~[?:3.2.0-e742d4aa] {re:classloading}
	at dev.fiki.forgehax.api.modloader.di.providers.ReflectionProviders$FieldProvider$$Lambda$3829/859033708.get(Unknown Source) ~[?:?] {}
	at java.util.Optional.orElseThrow(Optional.java:290) ~[?:1.8.0_51] {}
	at dev.fiki.forgehax.api.modloader.di.providers.ReflectionProviders$FieldProvider.getInstance(ReflectionProviders.java:62) ~[?:3.2.0-e742d4aa] {re:classloading}
	at dev.fiki.forgehax.api.modloader.di.providers.DependencyProvider$LoadChain.getOrCreate(DependencyProvider.java:84) ~[?:3.2.0-e742d4aa] {re:classloading}
	at dev.fiki.forgehax.api.modloader.di.providers.SingletonDependency.getInstance(SingletonDependency.java:69) ~[?:3.2.0-e742d4aa] {re:classloading}
	at dev.fiki.forgehax.api.modloader.di.providers.DependencyProvider$LoadChain.getOrCreate(DependencyProvider.java:84) ~[?:3.2.0-e742d4aa] {re:classloading}
	at dev.fiki.forgehax.api.modloader.di.providers.SingletonDependency.getInstance(SingletonDependency.java:69) ~[?:3.2.0-e742d4aa] {re:classloading}
	at dev.fiki.forgehax.api.modloader.di.providers.DependencyProvider.getInstance(DependencyProvider.java:30) ~[?:3.2.0-e742d4aa] {re:classloading}
	at dev.fiki.forgehax.api.modloader.di.DependencyInjector.getSingletonInstance(DependencyInjector.java:138) ~[?:3.2.0-e742d4aa] {re:classloading}
	at dev.fiki.forgehax.api.modloader.di.DependencyInjector$$Lambda$3896/455646417.apply(Unknown Source) ~[?:?] {}
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193) ~[?:1.8.0_51] {}
	at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:175) ~[?:1.8.0_51] {}
	at java.util.TreeMap$KeySpliterator.forEachRemaining(TreeMap.java:2742) ~[?:1.8.0_51] {}
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:512) ~[?:1.8.0_51] {}
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:502) ~[?:1.8.0_51] {}
	at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:151) ~[?:1.8.0_51] {}
	at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:174) ~[?:1.8.0_51] {}
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:1.8.0_51] {}
	at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:418) ~[?:1.8.0_51] {}
	at dev.fiki.forgehax.api.modloader.ModManager.startupMods(ModManager.java:114) ~[?:3.2.0-e742d4aa] {re:classloading}
	at dev.fiki.forgehax.main.ForgeHax.setup(ForgeHax.java:118) ~[?:3.2.0-e742d4aa] {re:classloading}
	at dev.fiki.forgehax.main.ForgeHax$$Lambda$3112/792725227.accept(Unknown Source) ~[?:?] {}
	at net.minecraftforge.eventbus.EventBus.doCastFilter(EventBus.java:247) ~[eventbus-3.0.5-service.jar:?] {}
	at net.minecraftforge.eventbus.EventBus.lambda$addListener$11(EventBus.java:239) ~[eventbus-3.0.5-service.jar:?] {}
	at net.minecraftforge.eventbus.EventBus$$Lambda$2935/1994984869.invoke(Unknown Source) ~[?:?] {}
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:297) ~[eventbus-3.0.5-service.jar:?] {}
	at net.minecraftforge.fml.javafmlmod.FMLModContainer.acceptEvent(FMLModContainer.java:120) ~[?:35.1] {re:classloading}
	at net.minecraftforge.fml.ModContainer.lambda$buildTransitionHandler$4(ModContainer.java:121) ~[?:?] {re:classloading}
	at net.minecraftforge.fml.ModContainer$$Lambda$3106/2040008077.run(Unknown Source) ~[?:?] {}
	at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1618) ~[?:1.8.0_51] {}
	at java.util.concurrent.CompletableFuture$AsyncRun.exec(CompletableFuture.java:1610) ~[?:1.8.0_51] {}
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289) ~[?:1.8.0_51] {}
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056) ~[?:1.8.0_51] {}
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1689) ~[?:1.8.0_51] {re:computing_frames}
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157) ~[?:1.8.0_51] {}

-- System Details --
Details:
	Minecraft Version: 1.16.4
	Minecraft Version ID: 1.16.4
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 1388342456 bytes (1324 MB) / 1879048192 bytes (1792 MB) up to 2147483648 bytes (2048 MB)
	CPUs: 4
	JVM Flags: 9 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx2G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	ModLauncher: 8.0.6+85+master.325de55
	ModLauncher launch target: fmlclient
	ModLauncher naming: srg
	ModLauncher services: 
		/mixin-0.8.2.jar mixin PLUGINSERVICE 
		/eventbus-3.0.5-service.jar eventbus PLUGINSERVICE 
		/forge-1.16.4-35.1.0.jar object_holder_definalize PLUGINSERVICE 
		/forge-1.16.4-35.1.0.jar runtime_enum_extender PLUGINSERVICE 
		/accesstransformers-2.2.0-shadowed.jar accesstransformer PLUGINSERVICE 
		/forge-1.16.4-35.1.0.jar capability_inject_definalize PLUGINSERVICE 
		/forge-1.16.4-35.1.0.jar runtimedistcleaner PLUGINSERVICE 
		/mixin-0.8.2.jar mixin TRANSFORMATIONSERVICE 
		/OptiFine_1.16.4_HD_U_G5.jar OptiFine TRANSFORMATIONSERVICE 
		/forge-1.16.4-35.1.0.jar fml TRANSFORMATIONSERVICE 
		/ForgeHax-1.16.4-3.2.0-e742d4aa.jar ForgeHaxCore TRANSFORMATIONSERVICE 
	FML: 35.1
	Forge: net.minecraftforge:35.1.0
	FML Language Providers: 
		javafml@35.1
		minecraft@1
	Mod List: 
		forge-1.16.4-35.1.0-client.jar                    |Minecraft                     |minecraft                     |1.16.4              |ENQUEUE_IM|NOSIGNATURE
		BetterPvP_20.28.2_Forge_1.16.4.jar                |Better PVP Mod                |xaerobetterpvp                |20.28.2             |ENQUEUE_IM|NOSIGNATURE
		ForgeHax-1.16.4-3.2.0-e742d4aa.jar                |ForgeHax                      |forgehax                      |3.2.0-e742d4aa      |ERROR     |NOSIGNATURE
		forge-1.16.4-35.1.0-universal.jar                 |Forge                         |forge                         |35.1.0              |ENQUEUE_IM|22:af:21:d8:19:82:7f:93:94:fe:2b:ac:b7:e4:41:57:68:39:87:b1:a7:5c:c6:44:f9:25:74:21:14:f5:0d:90
	Crash Report UUID: 1b132517-e38a-48c3-9469-36a765b6337c
	OptiFine Version: OptiFine_1.16.4_HD_U_G5
	OptiFine Build: 20201106-171901
	Render Distance Chunks: 6
	Mipmaps: 4
	Anisotropic Filtering: 1
	Antialiasing: 0
	Multitexture: false
	Shaders: null
	OpenGlVersion: 4.4.0 - Build 20.19.15.4835
	OpenGlRenderer: Intel(R) HD Graphics 5500
	OpenGlVendor: Intel
	CpuCount: 4

**Comment by fr1kin** [comment]
Looks like the annotation processor isn't being run for the Jenkins builds

**Comment by fr1kin** [comment]
Stupid build issue with jenkins. I'll have it fixed soonish

**Comment by Zynph** [comment]
Got the same issue any work around for now?

**Comment by fr1kin** [comment]
Download https://jenkins.nhackindustries.com/job/ForgeHax/job/1.16/35/

**Comment by fr1kin** [comment]
Fixed in https://github.com/fr1kin/ForgeHax/commit/9a7e575dac5e3453423892d93d3306d8a2112e50
