### ISSUE TITLE
[1.12] ForgeHax delays Minecraft launch for ~2 minutes

### ISSUE THREAD

**Issue by Thedeur** [fr1kin/ForgeHax#410]
FH Version 2.9.0
Minecraft 1.12.2
Forge 14.23.5.2847

Just to note, this isn't crashing, but it feels like it's skirting the edge. Here's the initial message printed, indicating there's something wrong. 

`[main/ERROR] [FML]: FML appears to be missing any signature data. This is not a good thing`

Then after a minute or two, an entire block of errors print out. 

`[main/ERROR] [ForgeHaxAsmStackTrace]: java.io.IOException: Server returned HTTP response code: 522 for URL: http://export.mcpbot.bspk.rs/mcp/1.12/mcp-1.12-srg.zip
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1897)
	at sun.net.www.protocol.http.HttpURLConnection.access$200(HttpURLConnection.java:92)
	at sun.net.www.protocol.http.HttpURLConnection$9.run(HttpURLConnection.java:1487)
	at sun.net.www.protocol.http.HttpURLConnection$9.run(HttpURLConnection.java:1485)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.AccessController.doPrivilegedWithCombiner(AccessController.java:784)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1484)
	at bspkrs.mmv.RemoteZipHandler.checkRemoteZip(RemoteZipHandler.java:107)
	at com.matt.forgehax.asm.utils.remapping.MCPMappingLoader.getSubDirForZip(MCPMappingLoader.java:106)
	at com.matt.forgehax.asm.utils.remapping.MCPMappingLoader.<init>(MCPMappingLoader.java:48)
	at com.matt.forgehax.asm.utils.remapping.ObfuscatedStateMapper.<init>(ObfuscatedStateMapper.java:49)
	at com.matt.forgehax.asm.utils.remapping.ObfuscatedStateMapper.getInstance(ObfuscatedStateMapper.java:36)
	at com.matt.forgehax.asm.utils.environment.RuntimeState.getMapper(RuntimeState.java:72)
	at com.matt.forgehax.asm.ASMCommon.<clinit>(ASMCommon.java:14)
	at com.matt.forgehax.asm.utils.asmtype.builders.ASMClassBuilder.attemptAutoAssign(ASMClassBuilder.java:59)
	at com.matt.forgehax.asm.utils.asmtype.builders.ASMClassBuilder.build(ASMClassBuilder.java:65)
	at com.matt.forgehax.asm.TypesMc$Classes.<clinit>(TypesMc.java:23)
	at com.matt.forgehax.asm.patches.BlockPatch.<init>(BlockPatch.java:22)
	at com.matt.forgehax.asm.ForgeHaxTransformer.<init>(ForgeHaxTransformer.java:51)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at java.lang.Class.newInstance(Class.java:442)
	at net.minecraftforge.fml.common.asm.ASMTransformerWrapper$TransformerWrapper.<init>(ASMTransformerWrapper.java:243)
	at $wrapper.com.matt.forgehax.asm.ForgeHaxTransformer.<init>(Unknown Source)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at java.lang.Class.newInstance(Class.java:442)
	at net.minecraft.launchwrapper.LaunchClassLoader.registerTransformer(LaunchClassLoader.java:88)
	at net.minecraftforge.fml.relauncher.CoreModManager$FMLPluginWrapper.injectIntoClassLoader(CoreModManager.java:132)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:115)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:210)
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:245)
	at org.multimc.EntryPoint.listen(EntryPoint.java:143)
	at org.multimc.EntryPoint.main(EntryPoint.java:34)`

Then the game launches after another pause. 

I was using this in a modpack initially, but even after disabling everything but FH still results in this unusual delay. Something tells me this could be network related?

**Comment by fr1kin** [comment]
You need to download the latest 1.12.2 build. Its failing to download a mapping file that is no longer accessible

**Comment by Thedeur** [comment]
Wow that was a quick response. Thanks, it works flawlessly now :)
