### ISSUE TITLE
forgehax crashes when starts

### ISSUE THREAD

**Issue by shimawari** [fr1kin/ForgeHax#461]
crashes when starting minecraft 
log:

```
[18:15:23] [main/INFO] [LaunchWrapper]: Loading tweak class name net.minecraftforge.fml.common.launcher.FMLTweaker
[18:15:23] [main/INFO] [LaunchWrapper]: Using primary tweak class name net.minecraftforge.fml.common.launcher.FMLTweaker
[18:15:23] [main/INFO] [LaunchWrapper]: Calling tweak class net.minecraftforge.fml.common.launcher.FMLTweaker
[18:15:23] [main/INFO] [FML]: Forge Mod Loader version 14.23.5.2860 for Minecraft 1.12.2 loading
[18:15:23] [main/INFO] [FML]: Java is Java HotSpot(TM) 64-Bit Server VM, version 1.8.0_51, running on Windows 10:amd64:10.0, installed at D:\WpSystem\S-1-5-21-467056614-557789165-3003433197-1001\AppData\Local\Packages\Microsoft.4297127D64EC6_8wekyb3d8bbwe\LocalCache\Local\runtime\jre-legacy\windows-x64\jre-legacy
[18:15:23] [main/INFO] [FML]: Searching C:\Users\Lenovo\AppData\Roaming\.minecraft(1.12.2forge)\mods for mods
[18:15:23] [main/WARN] [FML]: Found FMLCorePluginContainsFMLMod marker in forgehax-1.12.2-2.9.0.jar. This is not recommended, @Mods should be in a separate jar from the coremod.
[18:15:23] [main/WARN] [FML]: The coremod com.matt.forgehax.asm.ForgeHaxCoreMod does not have a MCVersion annotation, it may cause issues with this version of Minecraft
[18:15:23] [main/WARN] [FML]: The coremod ForgeHaxCoreMod (com.matt.forgehax.asm.ForgeHaxCoreMod) is not signed!
[18:15:23] [main/INFO] [FML]: Loading tweaker org.spongepowered.asm.launch.MixinTweaker from lambda-3.4.0.jar
[18:15:23] [main/INFO] [FML]: Loading tweaker optifine.OptiFineForgeTweaker from OptiFine_1.12.2_HD_U_E3.jar
[18:15:23] [main/WARN] [FML]: Found FMLCorePluginContainsFMLMod marker in Xaeros_Minimap_24.2.0_Forge_1.12.jar. This is not recommended, @Mods should be in a separate jar from the coremod.
[18:15:23] [main/WARN] [FML]: The coremod XaeroMinimapPlugin (xaero.common.core.XaeroMinimapPlugin) is not signed!
[18:15:23] [main/INFO] [LaunchWrapper]: Loading tweak class name net.minecraftforge.fml.common.launcher.FMLInjectionAndSortingTweaker
[18:15:23] [main/INFO] [LaunchWrapper]: Loading tweak class name org.spongepowered.asm.launch.MixinTweaker
[18:15:23] [main/INFO] [mixin]: SpongePowered MIXIN Subsystem Version=0.8.5 Source=file:/C:/Users/Lenovo/AppData/Roaming/.minecraft(1.12.2forge)/mods/lambda-3.4.0.jar Service=LaunchWrapper Env=CLIENT
[18:15:24] [main/WARN] [FML]: The coremod LambdaCoreMod (com.lambda.client.LambdaCoreMod) is not signed!
[18:15:24] [main/INFO] [mixin]: Compatibility level set to JAVA_8
[18:15:24] [main/ERROR] [mixin]: Mixin config mixins.lambda.json does not specify "minVersion" property
[18:15:24] [main/ERROR] [mixin]: Mixin config mixins.baritone.json does not specify "minVersion" property
[18:15:24] [main/INFO] [Lambda]: Lambda and Baritone mixins initialised. (searge)
[18:15:24] [main/INFO] [LaunchWrapper]: Loading tweak class name optifine.OptiFineForgeTweaker
[18:15:24] [main/INFO] [LaunchWrapper]: Loading tweak class name net.minecraftforge.fml.common.launcher.FMLDeobfTweaker
[18:15:24] [main/INFO] [LaunchWrapper]: Calling tweak class net.minecraftforge.fml.common.launcher.FMLInjectionAndSortingTweaker
[18:15:24] [main/INFO] [LaunchWrapper]: Calling tweak class net.minecraftforge.fml.common.launcher.FMLInjectionAndSortingTweaker
[18:15:24] [main/INFO] [LaunchWrapper]: Calling tweak class optifine.OptiFineForgeTweaker
[18:15:24] [main/INFO] [STDOUT]: [optifine.OptiFineForgeTweaker:dbg:56]: OptiFineForgeTweaker: acceptOptions
[18:15:24] [main/INFO] [STDOUT]: [optifine.OptiFineForgeTweaker:dbg:56]: OptiFineForgeTweaker: injectIntoClassLoader
[18:15:24] [main/INFO] [STDOUT]: [optifine.OptiFineClassTransformer:dbg:221]: OptiFine ClassTransformer
[18:15:24] [main/INFO] [STDOUT]: [optifine.OptiFineClassTransformer:dbg:221]: OptiFine ZIP file: C:\Users\Lenovo\AppData\Roaming\.minecraft(1.12.2forge)\mods\OptiFine_1.12.2_HD_U_E3.jar
[18:15:24] [main/INFO] [LaunchWrapper]: Calling tweak class net.minecraftforge.fml.relauncher.CoreModManager$FMLPluginWrapper
[18:15:28] [main/INFO] [FML]: Found valid fingerprint for Minecraft Forge. Certificate fingerprint e3c3d50c7c986df74c645c0ac54639741c90a557
[18:15:28] [main/INFO] [FML]: Found valid fingerprint for Minecraft. Certificate fingerprint cd99959656f753dc28d863b46769f7f8fbaefcfc
[18:15:28] [main/INFO] [LaunchWrapper]: Calling tweak class net.minecraftforge.fml.relauncher.CoreModManager$FMLPluginWrapper
[18:15:28] [main/INFO] [LaunchWrapper]: Calling tweak class net.minecraftforge.fml.relauncher.CoreModManager$FMLPluginWrapper
[18:15:28] [main/INFO] [ForgeHaxASM]: Using build mapping "1.12_snapshot_20171003"
[18:15:30] [main/ERROR] [ForgeHaxAsmStackTrace]: javax.net.ssl.SSLHandshakeException: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
	at sun.security.ssl.Alerts.getSSLException(Alerts.java:192)
	at sun.security.ssl.SSLSocketImpl.fatal(SSLSocketImpl.java:1949)
	at sun.security.ssl.Handshaker.fatalSE(Handshaker.java:302)
	at sun.security.ssl.Handshaker.fatalSE(Handshaker.java:296)
	at sun.security.ssl.ClientHandshaker.serverCertificate(ClientHandshaker.java:1497)
	at sun.security.ssl.ClientHandshaker.processMessage(ClientHandshaker.java:212)
	at sun.security.ssl.Handshaker.processLoop(Handshaker.java:979)
	at sun.security.ssl.Handshaker.process_record(Handshaker.java:914)
	at sun.security.ssl.SSLSocketImpl.readRecord(SSLSocketImpl.java:1062)
	at sun.security.ssl.SSLSocketImpl.performInitialHandshake(SSLSocketImpl.java:1375)
	at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:1403)
	at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:1387)
	at sun.net.www.protocol.https.HttpsClient.afterConnect(HttpsClient.java:563)
	at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(AbstractDelegateHttpsURLConnection.java:185)
	at sun.net.www.protocol.http.HttpURLConnection.followRedirect0(HttpURLConnection.java:2661)
	at sun.net.www.protocol.http.HttpURLConnection.access$300(HttpURLConnection.java:90)
	at sun.net.www.protocol.http.HttpURLConnection$12.run(HttpURLConnection.java:2574)
	at sun.net.www.protocol.http.HttpURLConnection$12.run(HttpURLConnection.java:2572)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.AccessController.doPrivileged(AccessController.java:713)
	at sun.net.www.protocol.http.HttpURLConnection.followRedirect(HttpURLConnection.java:2571)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1769)
	at sun.net.www.protocol.http.HttpURLConnection.access$200(HttpURLConnection.java:90)
	at sun.net.www.protocol.http.HttpURLConnection$9.run(HttpURLConnection.java:1432)
	at sun.net.www.protocol.http.HttpURLConnection$9.run(HttpURLConnection.java:1430)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.AccessController.doPrivileged(AccessController.java:713)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1429)
	at sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:254)
	at bspkrs.mmv.RemoteZipHandler.checkRemoteZip(RemoteZipHandler.java:107)
	at com.matt.forgehax.asm.utils.remapping.MCPMappingLoader.getSubDirForZip(MCPMappingLoader.java:106)
	at com.matt.forgehax.asm.utils.remapping.MCPMappingLoader.<init>(MCPMappingLoader.java:48)
	at com.matt.forgehax.asm.utils.remapping.ObfuscatedStateMapper.<init>(ObfuscatedStateMapper.java:49)
	at com.matt.forgehax.asm.utils.remapping.ObfuscatedStateMapper.getInstance(ObfuscatedStateMapper.java:36)
	at com.matt.forgehax.asm.utils.environment.RuntimeState.getMapper(RuntimeState.java:72)
	at com.matt.forgehax.asm.ASMCommon.<clinit>(ASMCommon.java:14)
	at com.matt.forgehax.asm.utils.asmtype.builders.ASMClassBuilder.attemptAutoAssign(ASMClassBuilder.java:59)
	at com.matt.forgehax.asm.utils.asmtype.builders.ASMClassBuilder.build(ASMClassBuilder.java:65)
	at com.matt.forgehax.asm.TypesMc$Classes.<clinit>(TypesMc.java:23)
	at com.matt.forgehax.asm.patches.BlockPatch.<init>(BlockPatch.java:22)
	at com.matt.forgehax.asm.ForgeHaxTransformer.<init>(ForgeHaxTransformer.java:51)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:422)
	at java.lang.Class.newInstance(Class.java:442)
	at net.minecraftforge.fml.common.asm.ASMTransformerWrapper$TransformerWrapper.<init>(ASMTransformerWrapper.java:243)
	at $wrapper.com.matt.forgehax.asm.ForgeHaxTransformer.<init>(Unknown Source)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:422)
	at java.lang.Class.newInstance(Class.java:442)
	at net.minecraft.launchwrapper.LaunchClassLoader.registerTransformer(LaunchClassLoader.java:88)
	at net.minecraftforge.fml.relauncher.CoreModManager$FMLPluginWrapper.injectIntoClassLoader(CoreModManager.java:132)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:115)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
Caused by: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
	at sun.security.validator.PKIXValidator.doBuild(PKIXValidator.java:387)
	at sun.security.validator.PKIXValidator.engineValidate(PKIXValidator.java:292)
	at sun.security.validator.Validator.validate(Validator.java:260)
	at sun.security.ssl.X509TrustManagerImpl.validate(X509TrustManagerImpl.java:324)
	at sun.security.ssl.X509TrustManagerImpl.checkTrusted(X509TrustManagerImpl.java:229)
	at sun.security.ssl.X509TrustManagerImpl.checkServerTrusted(X509TrustManagerImpl.java:124)
	at sun.security.ssl.ClientHandshaker.serverCertificate(ClientHandshaker.java:1479)
	... 52 more
Caused by: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
	at sun.security.provider.certpath.SunCertPathBuilder.build(SunCertPathBuilder.java:145)
	at sun.security.provider.certpath.SunCertPathBuilder.engineBuild(SunCertPathBuilder.java:131)
	at java.security.cert.CertPathBuilder.build(CertPathBuilder.java:280)
	at sun.security.validator.PKIXValidator.doBuild(PKIXValidator.java:382)
	... 58 more

[18:15:31] [main/ERROR] [ForgeHaxAsmStackTrace]: javax.net.ssl.SSLHandshakeException: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
	at sun.security.ssl.Alerts.getSSLException(Alerts.java:192)
	at sun.security.ssl.SSLSocketImpl.fatal(SSLSocketImpl.java:1949)
	at sun.security.ssl.Handshaker.fatalSE(Handshaker.java:302)
	at sun.security.ssl.Handshaker.fatalSE(Handshaker.java:296)
	at sun.security.ssl.ClientHandshaker.serverCertificate(ClientHandshaker.java:1497)
	at sun.security.ssl.ClientHandshaker.processMessage(ClientHandshaker.java:212)
	at sun.security.ssl.Handshaker.processLoop(Handshaker.java:979)
	at sun.security.ssl.Handshaker.process_record(Handshaker.java:914)
	at sun.security.ssl.SSLSocketImpl.readRecord(SSLSocketImpl.java:1062)
	at sun.security.ssl.SSLSocketImpl.performInitialHandshake(SSLSocketImpl.java:1375)
	at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:1403)
	at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:1387)
	at sun.net.www.protocol.https.HttpsClient.afterConnect(HttpsClient.java:563)
	at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(AbstractDelegateHttpsURLConnection.java:185)
	at sun.net.www.protocol.http.HttpURLConnection.followRedirect0(HttpURLConnection.java:2661)
	at sun.net.www.protocol.http.HttpURLConnection.access$300(HttpURLConnection.java:90)
	at sun.net.www.protocol.http.HttpURLConnection$12.run(HttpURLConnection.java:2574)
	at sun.net.www.protocol.http.HttpURLConnection$12.run(HttpURLConnection.java:2572)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.AccessController.doPrivileged(AccessController.java:713)
	at sun.net.www.protocol.http.HttpURLConnection.followRedirect(HttpURLConnection.java:2571)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1769)
	at sun.net.www.protocol.http.HttpURLConnection.access$200(HttpURLConnection.java:90)
	at sun.net.www.protocol.http.HttpURLConnection$9.run(HttpURLConnection.java:1432)
	at sun.net.www.protocol.http.HttpURLConnection$9.run(HttpURLConnection.java:1430)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.AccessController.doPrivileged(AccessController.java:713)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1429)
	at sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:254)
	at bspkrs.mmv.RemoteZipHandler.checkRemoteZip(RemoteZipHandler.java:107)
	at com.matt.forgehax.asm.utils.remapping.MCPMappingLoader.getSubDirForZip(MCPMappingLoader.java:106)
	at com.matt.forgehax.asm.utils.remapping.MCPMappingLoader.<init>(MCPMappingLoader.java:49)
	at com.matt.forgehax.asm.utils.remapping.ObfuscatedStateMapper.<init>(ObfuscatedStateMapper.java:49)
	at com.matt.forgehax.asm.utils.remapping.ObfuscatedStateMapper.getInstance(ObfuscatedStateMapper.java:36)
	at com.matt.forgehax.asm.utils.environment.RuntimeState.getMapper(RuntimeState.java:72)
	at com.matt.forgehax.asm.ASMCommon.<clinit>(ASMCommon.java:14)
	at com.matt.forgehax.asm.utils.asmtype.builders.ASMClassBuilder.attemptAutoAssign(ASMClassBuilder.java:59)
	at com.matt.forgehax.asm.utils.asmtype.builders.ASMClassBuilder.build(ASMClassBuilder.java:65)
	at com.matt.forgehax.asm.TypesMc$Classes.<clinit>(TypesMc.java:23)
	at com.matt.forgehax.asm.patches.BlockPatch.<init>(BlockPatch.java:22)
	at com.matt.forgehax.asm.ForgeHaxTransformer.<init>(ForgeHaxTransformer.java:51)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:422)
	at java.lang.Class.newInstance(Class.java:442)
	at net.minecraftforge.fml.common.asm.ASMTransformerWrapper$TransformerWrapper.<init>(ASMTransformerWrapper.java:243)
	at $wrapper.com.matt.forgehax.asm.ForgeHaxTransformer.<init>(Unknown Source)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:422)
	at java.lang.Class.newInstance(Class.java:442)
	at net.minecraft.launchwrapper.LaunchClassLoader.registerTransformer(LaunchClassLoader.java:88)
	at net.minecraftforge.fml.relauncher.CoreModManager$FMLPluginWrapper.injectIntoClassLoader(CoreModManager.java:132)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:115)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
Caused by: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
	at sun.security.validator.PKIXValidator.doBuild(PKIXValidator.java:387)
	at sun.security.validator.PKIXValidator.engineValidate(PKIXValidator.java:292)
	at sun.security.validator.Validator.validate(Validator.java:260)
	at sun.security.ssl.X509TrustManagerImpl.validate(X509TrustManagerImpl.java:324)
	at sun.security.ssl.X509TrustManagerImpl.checkTrusted(X509TrustManagerImpl.java:229)
	at sun.security.ssl.X509TrustManagerImpl.checkServerTrusted(X509TrustManagerImpl.java:124)
	at sun.security.ssl.ClientHandshaker.serverCertificate(ClientHandshaker.java:1479)
	... 52 more
Caused by: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
	at sun.security.provider.certpath.SunCertPathBuilder.build(SunCertPathBuilder.java:145)
	at sun.security.provider.certpath.SunCertPathBuilder.engineBuild(SunCertPathBuilder.java:131)
	at java.security.cert.CertPathBuilder.build(CertPathBuilder.java:280)
	at sun.security.validator.PKIXValidator.doBuild(PKIXValidator.java:382)
	... 58 more

[18:15:31] [main/ERROR] [ForgeHaxASM]: Unable to find joined.srg. Your MCP conf folder may be corrupt.
[18:15:31] [main/ERROR] [ForgeHaxAsmStackTrace]: com.matt.forgehax.asm.utils.remapping.MCPMappingLoader$CantLoadMCPMappingException: Unable to find joined.srg. Your MCP conf folder may be corrupt.
	at com.matt.forgehax.asm.utils.remapping.MCPMappingLoader.<init>(MCPMappingLoader.java:56)
	at com.matt.forgehax.asm.utils.remapping.ObfuscatedStateMapper.<init>(ObfuscatedStateMapper.java:49)
	at com.matt.forgehax.asm.utils.remapping.ObfuscatedStateMapper.getInstance(ObfuscatedStateMapper.java:36)
	at com.matt.forgehax.asm.utils.environment.RuntimeState.getMapper(RuntimeState.java:72)
	at com.matt.forgehax.asm.ASMCommon.<clinit>(ASMCommon.java:14)
	at com.matt.forgehax.asm.utils.asmtype.builders.ASMClassBuilder.attemptAutoAssign(ASMClassBuilder.java:59)
	at com.matt.forgehax.asm.utils.asmtype.builders.ASMClassBuilder.build(ASMClassBuilder.java:65)
	at com.matt.forgehax.asm.TypesMc$Classes.<clinit>(TypesMc.java:23)
	at com.matt.forgehax.asm.patches.BlockPatch.<init>(BlockPatch.java:22)
	at com.matt.forgehax.asm.ForgeHaxTransformer.<init>(ForgeHaxTransformer.java:51)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:422)
	at java.lang.Class.newInstance(Class.java:442)
	at net.minecraftforge.fml.common.asm.ASMTransformerWrapper$TransformerWrapper.<init>(ASMTransformerWrapper.java:243)
	at $wrapper.com.matt.forgehax.asm.ForgeHaxTransformer.<init>(Unknown Source)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:422)
	at java.lang.Class.newInstance(Class.java:442)
	at net.minecraft.launchwrapper.LaunchClassLoader.registerTransformer(LaunchClassLoader.java:88)
	at net.minecraftforge.fml.relauncher.CoreModManager$FMLPluginWrapper.injectIntoClassLoader(CoreModManager.java:132)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:115)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

[18:15:31] [main/INFO] [ForgeHaxASM]: Mapping data successfully initialize
[18:15:31] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:1052]: java.lang.ExceptionInInitializerError
[18:15:31] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at com.matt.forgehax.asm.utils.asmtype.builders.ASMClassBuilder.attemptAutoAssign(ASMClassBuilder.java:59)
[18:15:31] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at com.matt.forgehax.asm.utils.asmtype.builders.ASMClassBuilder.build(ASMClassBuilder.java:65)
[18:15:31] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at com.matt.forgehax.asm.TypesMc$Classes.<clinit>(TypesMc.java:23)
[18:15:31] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at com.matt.forgehax.asm.patches.BlockPatch.<init>(BlockPatch.java:22)
[18:15:31] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at com.matt.forgehax.asm.ForgeHaxTransformer.<init>(ForgeHaxTransformer.java:51)
[18:15:31] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
[18:15:31] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
[18:15:31] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
[18:15:31] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at java.lang.reflect.Constructor.newInstance(Constructor.java:422)
[18:15:31] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at java.lang.Class.newInstance(Class.java:442)
[18:15:31] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at net.minecraftforge.fml.common.asm.ASMTransformerWrapper$TransformerWrapper.<init>(ASMTransformerWrapper.java:243)
[18:15:31] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at $wrapper.com.matt.forgehax.asm.ForgeHaxTransformer.<init>(Unknown Source)
[18:15:31] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
[18:15:31] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
[18:15:31] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
[18:15:31] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at java.lang.reflect.Constructor.newInstance(Constructor.java:422)
[18:15:31] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at java.lang.Class.newInstance(Class.java:442)
[18:15:31] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at net.minecraft.launchwrapper.LaunchClassLoader.registerTransformer(LaunchClassLoader.java:88)
[18:15:31] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at net.minecraftforge.fml.relauncher.CoreModManager$FMLPluginWrapper.injectIntoClassLoader(CoreModManager.java:132)
[18:15:31] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at net.minecraft.launchwrapper.Launch.launch(Launch.java:115)
[18:15:31] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
[18:15:31] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:1061]: Caused by: java.lang.NullPointerException: MCPMappingLoader failed to lookup obfuscation data
[18:15:31] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:1061]: 	at java.util.Objects.requireNonNull(Objects.java:228)
[18:15:31] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:1061]: 	at com.matt.forgehax.asm.utils.remapping.ObfuscatedStateMapper.<init>(ObfuscatedStateMapper.java:57)
[18:15:31] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:1061]: 	at com.matt.forgehax.asm.utils.remapping.ObfuscatedStateMapper.getInstance(ObfuscatedStateMapper.java:36)
[18:15:31] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:1061]: 	at com.matt.forgehax.asm.utils.environment.RuntimeState.getMapper(RuntimeState.java:72)
[18:15:31] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:1061]: 	at com.matt.forgehax.asm.ASMCommon.<clinit>(ASMCommon.java:14)
[18:15:31] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:1061]: 	... 21 more

```
i think it might have something to do with the mcpmappingloader

**Comment by fr1kin** [comment]
Probably using a version of ForgeHax 1.12.2 that doesn't have the updated MCP mapping link. https://github.com/fr1kin/ForgeHax/releases/tag/2.9.0

**Comment by shimawari** [comment]
> Probably using a version of ForgeHax 1.12.2 that doesn't have the updated MCP mapping link. https://github.com/fr1kin/ForgeHax/releases/tag/2.9.0'

i have used the latest version of ForgeHax 1.12.2, and the log still says the same
what did i do wrong?

**Comment by fr1kin** [comment]
Maybe you are using an ancient JDK version?

**Comment by shimawari** [comment]
I used java 1.8.0_361

**Comment by fr1kin** [comment]
perhaps try using the latest version (422)

edit: you are running an ancient version of java. `Java is Java HotSpot(TM) 64-Bit Server VM, version 1.8.0_51`

**Comment by shimawari** [comment]
sorry, didn't see that
