### ISSUE TITLE
ConcurrentModificationException in ChatIdentifierService

### ISSUE THREAD

**Issue by VADemon** [fr1kin/ForgeHax#81]
```[Netty Client IO #16/ERROR]: Exception caught during firing event com.matt.forgehax.asm.events.PacketEvent$Incoming$Pre@7ed4fa36:
java.util.ConcurrentModificationException: null
	at java.util.HashMap$HashIterator.nextNode(HashMap.java:1442) ~[?:1.8.0_191]
	at java.util.HashMap$ValueIterator.next(HashMap.java:1471) ~[?:1.8.0_191]
	at com.matt.forgehax.mods.services.ChatIdentifierService.extract(ChatIdentifierService.java:52) ~[ChatIdentifierService.class:?]
	at com.matt.forgehax.mods.services.ChatIdentifierService.onChatMessage(ChatIdentifierService.java:75) ~[ChatIdentifierService.class:?]
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_93_ChatIdentifierService_onChatMessage_Pre.invoke(.dynamic) ~[?:?]
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90) ~[ASMEventHandler.class:?]
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182) [EventBus.class:?]
	at com.matt.forgehax.asm.ForgeHaxHooks.onPreReceived(ForgeHaxHooks.java:175) [ForgeHaxHooks.class:?]
	at net.minecraft.network.NetworkManager.channelRead0(NetworkManager.java:147) [gw.class:?]
...
```
I entered depression after the kick from the server.

**Comment by fr1kin** [comment]
I haven't actually tested my fix, but in theory it should work.
